### ISSUE TITLE
3.2.2 柯里化第二段代码并没有直接输出结果

### ISSUE THREAD

**Issue by Ahacad** [coffe1891/frontend-hard-mode-interview#13]
[这一节的第二段代码](https://github.com/coffe1891/frontend-hard-mode-interview/blob/master/1/1.3.2.md#2-%E5%BB%B6%E8%BF%9F%E8%BF%90%E8%A1%8C)，运行`sum(4)`后似乎并没有直接输出结果。与第一段代码的区别很小，引入了 `length` 但是后续并没有使用，可能是写错了？

**Comment by coffe1891** [comment]
确实写错了，择日修复

**Comment by coffe1891** [comment]
确实写错了，择日修复
