### ISSUE TITLE
纠正一下

### ISSUE THREAD

**Issue by ChYuanJinlin** [coffe1891/frontend-hard-mode-interview#3]
函数作用域 那里b 应该是未定义，不应该是undefined

**Comment by coffe1891** [comment]
已经修正。感谢提醒，还请以后多多指出错漏之处

**Comment by ChYuanJinlin** [comment]
没事，文章的写的不错，还需要向大佬多学习



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bob Ma"<notifications@github.com&gt;; 
发送时间: 2020年6月29日(星期一) 下午4:13
收件人: "coffe1891/frontend-hard-mode-interview"<frontend-hard-mode-interview@noreply.github.com&gt;; 
抄送: "幸福的宝贝"<1075360356@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [coffe1891/frontend-hard-mode-interview] 纠正一下 (#3)





 
已经修正。感谢提醒，还请以后多多指出错漏之处
