### ISSUE TITLE
2.1.2 函数声明提升  代码示例错误反馈

### ISSUE THREAD

**Issue by xiaolong0114** [coffe1891/frontend-hard-mode-interview#7]
2.1.2 函数声明提升  中的代码

虽然此章节为重点讲解函数声明的提升，但是因为log了func1，所以此处建议进行修改

//函数的声明形态
function func0() {
  return 0;
}
console.log(func0); //>> func0() {return 0}
console.log(func1); //>> undefined
//函数的表达式形态
var func1 = function() {
  return 1;
};

应该为  

//变量声明提升
var func1
//函数的声明形态
function func0() {
  return 0;
}
console.log(func0); //>> func0() {return 0}
console.log(func1); //>> undefined
//函数的表达式形态
func1 = function() {
  return 1;
};

**Comment by coffe1891** [comment]
感谢提醒，已修正。

ps：你也可以fork一份本书，然后提交pull request，这样就更方便review代码进行交流了。
